### PR TITLE
make it real; also sprinkle some g-null chars in

### PR DESCRIPTION
**Pull request by Artoria2e5**
why don't we just zero-deliminate these things and also use the built-in head functionality of shuf

### CODE REVIEW

**Comment by Tao-Quixote** [comment]
Seems that `find -type f .` will not work, is it supposed to be something like `find . -type f` or `find / -type f`?

**Comment by Artoria2e5** [comment]
wait wait find accepts options *after* the directory? yeah it's supposed to be after it i guess...

**Comment by Artoria2e5** [comment]
oh i see. changing that too.

**Comment by Artoria2e5** [comment]
`find -f` is mainly for `rm` to not complain about dirs by the way. erasing an entire dir is definitely not the way to do "half" the files i figured..

**Comment by Tao-Quixote** [comment]
How about change the last part from `xargs -0 -- rm -f` to `xargs -0 -- rm -fr`?

**Comment by Artoria2e5** [comment]
`-type f` makes `rm -r` meaningless. also see comment above about "recursively"

**Pull request merged**
