### PR TITLE
Be more randomly

### PR DESCRIPTION
**Pull request by xyzsss**

### CODE REVIEW

**Comment by DengkeDu** [comment]
This will case problem when boot next time, so home dir will more appreciate.

**Comment by Artoria2e5** [comment]
this wont work because `find .` and `find /` gives different line counts usually

**Comment by DengkeDu** [comment]
Haha, we can test it on raspberrypi.

**Comment by hotvulcan** [comment]
Ok. I believe multi-universe, and we are all chrooted.  Powerful like Thanos may choose which universe to purge.  But He must step in it. So, he uses "." against "/".

**Comment by hotvulcan** [comment]
And Thanos knows he is Thanos.

**Pull request closed without merging**
